// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk7xDLGoy-Yfx-hYXd_YHSLM-Jaytv2xM',
    appId: '1:957084576686:web:0b800b50f527140530f63f',
    messagingSenderId: '957084576686',
    projectId: 'fir-1bdac',
    authDomain: 'fir-1bdac.firebaseapp.com',
    databaseURL:
        'https://fir-1bdac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-1bdac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHFXn_nL7JwnhIwEIPqdTcVj53yq_Qn-w',
    appId: '1:957084576686:android:12876fc523687fff30f63f',
    messagingSenderId: '957084576686',
    projectId: 'fir-1bdac',
    databaseURL:
        'https://fir-1bdac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-1bdac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZgyJpq_9YH4bec_z7xKpMb6o92AeYIE',
    appId: '1:957084576686:ios:14ec8e24faf5684e30f63f',
    messagingSenderId: '957084576686',
    projectId: 'fir-1bdac',
    databaseURL:
        'https://fir-1bdac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-1bdac.appspot.com',
    iosClientId:
        '957084576686-m44das8upb7heorrbmeh3v9la6147kbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZgyJpq_9YH4bec_z7xKpMb6o92AeYIE',
    appId: '1:957084576686:ios:14ec8e24faf5684e30f63f',
    messagingSenderId: '957084576686',
    projectId: 'fir-1bdac',
    databaseURL:
        'https://fir-1bdac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-1bdac.appspot.com',
    iosClientId:
        '957084576686-m44das8upb7heorrbmeh3v9la6147kbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
